#ifndef ARAPUCA_H
#define ARAPUCA_H

/* Warning: this file is autogenerated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque profile builder.
 */
typedef struct arapuca_ArapucaProfile arapuca_ArapucaProfile;

/**
 * Create a new profile builder.
 */
struct arapuca_ArapucaProfile *arapuca_profile_new(void);

/**
 * Add a read-only path to the profile. Returns 0 on success, -1 on error.
 *
 * # Safety
 *
 * `profile` must be a valid pointer from `arapuca_profile_new()`.
 * `path` must be a valid null-terminated UTF-8 string.
 */
int32_t arapuca_profile_add_read_path(struct arapuca_ArapucaProfile *profile,
                                        const char *path);

/**
 * Add a read-write path to the profile. Returns 0 on success, -1 on error.
 *
 * # Safety
 *
 * `profile` must be a valid pointer from `arapuca_profile_new()`.
 * `path` must be a valid null-terminated UTF-8 string.
 */
int32_t arapuca_profile_add_write_path(struct arapuca_ArapucaProfile *profile,
                                         const char *path);

/**
 * Set memory limit in MB.
 *
 * # Safety
 *
 * `profile` must be a valid pointer from `arapuca_profile_new()`.
 */
void arapuca_profile_set_memory_mb(struct arapuca_ArapucaProfile *profile, uint64_t mb);

/**
 * Set CPU percentage limit.
 *
 * # Safety
 *
 * `profile` must be a valid pointer from `arapuca_profile_new()`.
 */
void arapuca_profile_set_cpu_pct(struct arapuca_ArapucaProfile *profile, uint32_t pct);

/**
 * Set maximum PIDs.
 *
 * # Safety
 *
 * `profile` must be a valid pointer from `arapuca_profile_new()`.
 */
void arapuca_profile_set_max_pids(struct arapuca_ArapucaProfile *profile, uint32_t pids);

/**
 * Set maximum file size in MB (RLIMIT_FSIZE).
 *
 * # Safety
 *
 * `profile` must be a valid pointer from `arapuca_profile_new()`.
 */
void arapuca_profile_set_max_file_size_mb(struct arapuca_ArapucaProfile *profile,
                                            uint64_t mb);

/**
 * Enable/disable network namespace isolation.
 *
 * # Safety
 *
 * `profile` must be a valid pointer from `arapuca_profile_new()`.
 */
void arapuca_profile_set_netns(struct arapuca_ArapucaProfile *profile, bool enabled);

/**
 * Free a profile. Safe to call with NULL or after a previous free.
 *
 * # Safety
 *
 * `profile` must be NULL or a valid pointer from `arapuca_profile_new()`.
 */
void arapuca_profile_free(struct arapuca_ArapucaProfile *profile);

/**
 * Apply sandbox restrictions to the current process. Fail-closed.
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 *
 * `profile` must be a valid pointer from `arapuca_profile_new()`.
 */
int32_t arapuca_apply(const struct arapuca_ArapucaProfile *profile);

/**
 * Probe the Landlock ABI version. Returns 0 if unavailable.
 */
uint32_t arapuca_landlock_abi_version(void);

/**
 * Probe whether network namespace isolation is available.
 */
bool arapuca_netns_available(void);

/**
 * Get the last error message. Returns NULL if no error.
 *
 * The returned pointer is valid until the next arapuca call on
 * the same thread. Caller must NOT free it.
 */
const char *arapuca_last_error(void);

#endif  /* ARAPUCA_H */
